### ISSUE TITLE
vixio conflict with another syntax

### ISSUE THREAD

**Issue by ham1255** [iBlitzkriegi/Vixio#152]
**Describe the bug**
Bug what destroyes most of skript stuff

**To Reproduce**
1. do this code in your server with vixio 2.0.0
```
    set {_item} to "Ender pearl" parsed as item
    set name of {_item} to "&dSkyblock"        
    set lore of {_item} to "&f&lX/200"
    give player {_time}
#create a gui slot 9 of player with {_item} to close then run player command "Skyblock" #<---- skript gui addon
```
2. then if we are executing that code up ^ skript throws error with vixio
```
[09:47:52 INFO]: Ham1255 [72da5744-8ad7-467d-a320-94b94d9ad28b]: /server
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! [Skript] Severe Error:
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Something went horribly wrong with Skript.
[09:47:52 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:47:52 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:47:52 ERROR]: #!#! Following plugins are probably related to this error in some way:
[09:47:52 ERROR]: #!#! Vixio (http://vixio.space)
[09:47:52 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:47:52 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:47:52 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:47:52 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:47:52 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Stack trace:
[09:47:52 ERROR]: #!#! java.lang.UnsupportedOperationException: This expression can only be changed using Vixio's changer effects. Please report how you got this error to show at https://github.com/iBlitzkriegi/Vixio/issues
[09:47:52 ERROR]: #!#! at me.iblitzkriegi.vixio.changers.ChangeableSimpleExpression.change(ChangeableSimpleExpression.java:13)
[09:47:52 ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[09:47:52 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[09:47:52 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:47:52 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[09:47:52 ERROR]: #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[09:47:52 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[09:47:52 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[09:47:52 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[09:47:52 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[09:47:52 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[09:47:52 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[09:47:52 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Version Information:
[09:47:52 ERROR]: #!#! Skript: 2.3.1 (latest)
[09:47:52 ERROR]: #!#! Flavor: skriptlang-github
[09:47:52 ERROR]: #!#! Date: 2019-01-05
[09:47:52 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
[09:47:52 ERROR]: #!#! Minecraft: 1.12.2
[09:47:52 ERROR]: #!#! Java: 1.8.0_192 (Java HotSpot(TM) 64-Bit Server VM 25.192-b12)
[09:47:52 ERROR]: #!#! OS: Linux amd64 4.15.0-43-generic
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Server platform: Paper
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Current node: null
[09:47:52 ERROR]: #!#! Current item: null
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Thread: Server thread
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! Language: english
[09:47:52 ERROR]: #!#! Link parse mode: DISABLED
[09:47:52 ERROR]: #!#!
[09:47:52 ERROR]: #!#! End of Error.
[09:47:52 ERROR]: #!#!
```

**Expected behavior**
item must be named to what i did set for
**Screenshots**
with vixio installed naming items does not work
https://cdn.discordapp.com/attachments/226682722679128065/532088860826402816/Untitled.png
with vixio not installed it does work 
https://cdn.discordapp.com/attachments/226682722679128065/532089636214800384/unknown.png
**Additional context**
paperspigot 1.12.2
skript dev37c - skript 2.3.1

**Comment by ham1255** [comment]
i have edited this becuase hastebin broke

**Comment by ham1255** [comment]
well that error does for me

**Comment by ham1255** [comment]
removing vixio solve the problem

**Comment by Pikachu920** [comment]
fact is the code above isn't what's causing the stacktrace

**Comment by ham1255** [comment]
@Pikachu920 Made an test server on my computer with thes plugin and paper spigot
![image](https://user-images.githubusercontent.com/34905970/50883680-3567dc80-1402-11e9-9449-49a3091bdf4a.png)
with this skript only 
![image](https://user-images.githubusercontent.com/34905970/50883757-6516e480-1402-11e9-9e34-4c8ffa155ff5.png)
and the console 
![image](https://user-images.githubusercontent.com/34905970/50883799-8ed00b80-1402-11e9-8296-6cec4349f5f3.png)
and here is a video
[https://youtu.be/qRGFaSvMlsQ](url)

**Comment by ham1255** [comment]
> fact is the code above isn't what's causing the stacktrace

**Comment by Pikachu920** [comment]
that code would cause it, yes. it's different than what you had in the original post

**Comment by ham1255** [comment]
well same you can do give {item} to player cause it someone reported it on discord support
![image](https://user-images.githubusercontent.com/34905970/50901090-960e0e00-1430-11e9-9548-a38495dcd96a.png)

**Comment by ham1255** [comment]
at least we need to fix this somehow

**Comment by iBlitzkriegi** [comment]
Rudely leaving the Discord means I can't even get anymore information about the issue from you... So thanks for that i guess.

**Comment by ham1255** [comment]
@iBlitzkriegi  its simple

just do this code with vixio installed
```
    set {_item} to "Ender pearl" parsed as item
    set name of {_item} to "better than orginal"        
    set lore of {_item} to "something else"
    give player {_time}
```

if  you remove     set name of {_item} to "better than orginal"
no error in the console

**Comment by ham1255** [comment]
> Rudely leaving the Discord means I can't even get anymore information about the issue from you... So thanks for that i guess.

i didnt leave the discord server?

**Comment by GamingGeek** [comment]
> 
> 
> > Rudely leaving the Discord means I can't even get anymore information about the issue from you... So thanks for that i guess.
> 
> i didnt leave the discord server?

Someone else was having a similar issue with conflicting syntax and was rude and left. He probably thought it was you.

**Comment by ham1255** [comment]
> > > Rudely leaving the Discord means I can't even get anymore information about the issue from you... So thanks for that i guess.
> > 
> > 
> > i didnt leave the discord server?
> 
> Someone else was having a similar issue with conflicting syntax and was rude and left. He probably thought it was you.

ikr like wtf i didnt leave the server

**Comment by ham1255** [comment]
still no update on this?

**Comment by iBlitzkriegi** [comment]
So after a while we've concluded this is due to a issue with vixio's changer system, It shouldn't be matching seeing as there is no bot in the event. This will be fixed by the next release, and if you need it urgently you can message me on Discord and ill just modify vixio's syntax until the fix is released

**Comment by ham1255** [comment]
Or just recomplie from github code

**Comment by carrymeonbedwars** [comment]
Please fix it
Because its Getting Bad for my server

**Comment by EnderDev** [comment]
Aww, you're scared. Removing my comments...

**Comment by carrymeonbedwars** [comment]
@iBlitzkriegi is been since a months that owner of this post @ham1255 created this

**Comment by GamingGeek** [comment]
@carrymeonbedwars yes but, did you read what blitz said?

**Comment by ham1255** [comment]
^^^^^^^

@carrymeonbedwars no need for tagging okay?

**Comment by carrymeonbedwars** [comment]
Bad dev

**Comment by carrymeonbedwars** [comment]
Shit dev like you never care about your users and just cancel the fucking project and delete your github i dont know how you support fucking toxic skript comunity

**Comment by ham1255** [comment]
@carrymeonbedwars  omg you cant read he fixed dam bug

**Comment by iBlitzkriegi** [comment]
Someone seems to be having a bad day. It was closed because it was fixed as the commit reference shows.

**Comment by ham1255** [comment]
Hey i would like to reopen this it's look like error gone but skript still wont able to rename item in var

**Comment by GamingGeek** [comment]
> 
> 
> Hey i would like to reopen this it's look like error gone but skript still wont able to rename item in var

did you get the version from Blitz?

**Comment by ham1255** [comment]
@GamingGeek  yes i did downloaded ti from github and complieded

**Comment by GamingGeek** [comment]
> 
> 
> @GamingGeek yes i did downloaded ti from github and complieded

🤔

**Comment by ham1255** [comment]
@GamingGeek 
![image](https://user-images.githubusercontent.com/34905970/55103493-f6ccee80-50e1-11e9-8b1d-572976dde134.png)

**Comment by GamingGeek** [comment]
> 
> 
> @GamingGeek
> ![image](https://user-images.githubusercontent.com/34905970/55103493-f6ccee80-50e1-11e9-8b1d-572976dde134.png)

ok?

**Comment by ham1255** [comment]
i clicked build.bat it created vixio to my desktop so it has 
fixed code right?

**Comment by GamingGeek** [comment]
> 
> 
> i clicked build.bat it created vixio to my desktop so it has
> fixed code right?

if you cloned the repo from the latest commit then yes it should.

**Comment by ham1255** [comment]
i did that but it still not working + there is no error on console anymore

**Comment by GamingGeek** [comment]
> 
> 
> i did that but it still not working + there is no error on console anymore

I'm as confused as you are. usually when blitz fixes something, it's fixed. that's why I said 🤔
